"""init

Revision ID: 0936b9a56f46
Revises: 
Create Date: 2019-01-22 09:46:49.451483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0936b9a56f46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('alias', sa.String(length=50), nullable=True),
    sa.Column('iframe', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('df_name', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('bg_color', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('df_name'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ovum',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('atpressure',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field')
    )
    op.create_table('bug1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('bug2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('bug3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('bug4',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('co2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('consumption',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('current1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('current2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('field_sensor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('sensor', sa.Integer(), nullable=False),
    sa.Column('df_name', sa.String(length=50), nullable=False),
    sa.Column('alias', sa.String(length=50), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('bg_color', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.ForeignKeyConstraint(['sensor'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field', 'df_name', name='UC_field_df_name')
    )
    op.create_table('humidity',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('k',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('luminance',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture10',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture4',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture5',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture6',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture7',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture8',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('moisture9',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('n',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('p',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph4',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph5',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('ph6',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('power1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('power2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('rainmeter',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec10',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec4',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec5',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec6',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec7',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec8',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soilec9',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp10',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp4',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp5',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp6',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp7',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp8',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('soiltemp9',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('spore',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('temperature',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('turmeric',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('user_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uv1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('uv2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('uv3',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('volt1',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('volt2',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    op.create_table('windspeed',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('field', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['field'], ['field.id'], ),
    sa.PrimaryKeyConstraint('timestamp', 'field'),
    sa.UniqueConstraint('field', 'timestamp', name='UC_field_time')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('windspeed')
    op.drop_table('volt2')
    op.drop_table('volt1')
    op.drop_table('uv3')
    op.drop_table('uv2')
    op.drop_table('uv1')
    op.drop_table('user_access')
    op.drop_table('turmeric')
    op.drop_table('temperature')
    op.drop_table('spore')
    op.drop_table('soiltemp9')
    op.drop_table('soiltemp8')
    op.drop_table('soiltemp7')
    op.drop_table('soiltemp6')
    op.drop_table('soiltemp5')
    op.drop_table('soiltemp4')
    op.drop_table('soiltemp3')
    op.drop_table('soiltemp2')
    op.drop_table('soiltemp10')
    op.drop_table('soiltemp1')
    op.drop_table('soilec9')
    op.drop_table('soilec8')
    op.drop_table('soilec7')
    op.drop_table('soilec6')
    op.drop_table('soilec5')
    op.drop_table('soilec4')
    op.drop_table('soilec3')
    op.drop_table('soilec2')
    op.drop_table('soilec10')
    op.drop_table('soilec1')
    op.drop_table('rainmeter')
    op.drop_table('power2')
    op.drop_table('power1')
    op.drop_table('ph6')
    op.drop_table('ph5')
    op.drop_table('ph4')
    op.drop_table('ph3')
    op.drop_table('ph2')
    op.drop_table('ph1')
    op.drop_table('p')
    op.drop_table('n')
    op.drop_table('moisture9')
    op.drop_table('moisture8')
    op.drop_table('moisture7')
    op.drop_table('moisture6')
    op.drop_table('moisture5')
    op.drop_table('moisture4')
    op.drop_table('moisture3')
    op.drop_table('moisture2')
    op.drop_table('moisture10')
    op.drop_table('moisture1')
    op.drop_table('luminance')
    op.drop_table('k')
    op.drop_table('humidity')
    op.drop_table('field_sensor')
    op.drop_table('current2')
    op.drop_table('current1')
    op.drop_table('consumption')
    op.drop_table('co2')
    op.drop_table('bug4')
    op.drop_table('bug3')
    op.drop_table('bug2')
    op.drop_table('bug1')
    op.drop_table('atpressure')
    op.drop_table('Ovum')
    op.drop_table('user')
    op.drop_table('sensor')
    op.drop_table('field')
    # ### end Alembic commands ###
