"""table user add column memo

Revision ID: 9e763dc831f8
Revises: 0936b9a56f46
Create Date: 2019-01-22 09:59:55.185614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e763dc831f8'
down_revision = '0936b9a56f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('memo', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'memo')
    # ### end Alembic commands ###
